name: Build DocEncryptor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows application
        run: |
          pyinstaller --onefile --windowed --name DocEncryptor app.py

      - name: Upload Windows application
        uses: actions/upload-artifact@v4
        with:
          name: DocEncryptor-Windows
          path: dist/DocEncryptor.exe


  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Universal macOS Executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --target-architecture universal2 DocEncryptor.py

      - name: Upload macOS application
        uses: actions/upload-artifact@v4
        with:
          name: DocEncryptor-macOS
          path: dist/DocEncryptor.app
